### ISSUE TITLE
Default command in readme has wrong syntax

### ISSUE THREAD

**Issue by HendrikSchmidt** [rvandewater/YAIB#131]
The example command to run training is missing a backslash and contains the seed twice leading to missed flags, it should probably be:

```
icu-benchmarks train \
    -d demo_data/mortality24/mimic_demo \
    -n mimic_demo \
    -t BinaryClassification \
    -tn Mortality24 \
    -m LGBMClassifier \
    -hp LGBMClassifier.min_child_samples=10 \
    --generate_cache \
    --load_cache \
    --seed 2222 \
    -l ../yaib_logs/ \
    --tune
```

**Comment by rvandewater** [comment]
Could you provide more details and try some debugging? I have not run into this issue.

**Comment by HendrikSchmidt** [comment]
> Could you provide more details and try some debugging? I have not run into this issue.

Found the real issue and completely changed the issue, didn't see your reply in time, sorry!
